baseURL = 'https://biestro.github.io/'
languageCode = 'en-us'
title = 'Alberto R. B.'


[markup]
  [markup.goldmark]
    [markup.renderer]
      unsafe = false  # Needed for inline HTML/MathJax
  [markup.highlight]
    style = "friendly"  # Choose a light theme
    guessSyntax = true

[menu]
  [[menu.main]]
    name = "/home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "/posts"
    url = "/posts/"
    weight = 20
    
  [[menu.main]]
    name = "/code"
    url = "https://github.com/biestro/BoundaryWall.jl?tab=readme-ov-file#boundarywalljl"
    weight = 30

[params]
  # Path relative to the 'static' folder
  profileImage = "/images/profile.jpg" 
  favicon = "/images/icosahedron.gif"
  
  
  # New fields
  authorName = "Alberto Ruiz-Biestro"
  authorDesc = """PhD Student in Physics at Rice University."""

